### ISSUE TITLE
\ecvworkexperience should span more than one page

### ISSUE THREAD

**Issue by lorebiga** [leinardi/europecv2013#10]
I'd have quite some content to describe my work experience, and this does not span more than one page. In other words, the whole \ecvworkexperience element appears in the second page, leaving a big blank area in the first page of my CV. Is there a way to have the content distribute in multiple pages?

**Comment by afcuttin** [comment]
I agree with this comment.
For long work experiences, the class should be able to insert a page break.

A possible workaround I use is to close the `\ecvitem` or  `\ecvworkexperience`, so that the page can break, and start a new one with an empty title, like so:
```
\ecvitem{title}{%
    very long stuff first part
} % close the item to allow page break
\ecvitem{}{ % empty, so as it acts as continuation of the previous one
    last part of the very long stuff
}
```
However, this break has to be manually inserted, therefore requiring adjustments any time the content of the cv is modified.

This also applies to the list of publications one may insert as part of the cv (which is my major concern).
If one has few publications, that fit in one page, the thing is manageable, otherwise the list has to be inserted by hand in an `itemize`-like environment, and then it has to be manually breaked like in the example before.
Other tricks can be used (like splitting the list of references by type of publication, [as proposed here](https://tex.stackexchange.com/a/307521/177)), but they fall short whenever the list spans more than one page.

The thing is that, to my understanding, this class uses a `longtable` approach, somewhat like the europecv class on CTAN (where the problem of the bibliography flowing out is clearly addressed).
Given that a row (that is, a `\ecvitem`) in a table cannot be split across pages, one has to manually split the content in different rows, so that the content can be properly typeset.

My conclusion is that I'll live with that, given that a solution to this problem will require a major overhaul of the class (which is very unlikely to happen).

**Comment by lorebiga** [comment]
Yes, let's live with this. On the workarounds, I suggest using \ecvitem, since \ecvworkexperience would keep some (empty) space at the top, in place of dates, institution, etc.
On the other hand, \ecvitem doesn't add the appropriate spacing at the end, to separate from the following \ecvworkexperience, but this can be fixed with a \par\vspace{6pt}.
I close this issue, then.
